
var headerText = "Corre Y Se Va!";
var footerText = "<a href='https://github.com/spacekidbeto/' target='_blank'>by RobertO HernandeZ</a>";
var winText = "WinneR";
var clickSnd = new Audio("audio/click.mp3");
var winSnd = new Audio("audio/win.mp3");

var JSONBingo = {"squares": [
        {"square": "<img id='pic' src='img/1 El Gallo.jpg'>"},
        {"square": "<img id='pic' src='img/2 El Diablito.jpg'>"},
        {"square": "<img id='pic' src='img/3 La Dama.jpg'>"},
        {"square": "<img id='pic' src='img/4 El Catrin.jpg'>"},
        {"square": "<img id='pic' src='img/5 El Paraguas.jpg'>"},
        {"square": "<img id='pic' src='img/6 La Sirena.jpg'>"},
        {"square": "<img id='pic' src='img/7 La Escalera.jpg'>"},
        {"square": "<img id='pic' src='img/8 La Botella.jpg'>"},
        {"square": "<img id='pic' src='img/9 El Barril.jpg'>"},
        {"square": "<img id='pic' src='img/10 El Arbol.jpg'>"},
        {"square": "<img id='pic' src='img/11 El Melon.jpg'>"},
        {"square": "<img id='pic' src='img/12 El Valiente.jpg'>"},
        {"square": "<img id='pic' src='img/13 El Gorrito.jpg'>"},
        {"square": "<img id='pic' src='img/14 La Muerte.jpg'>"},
        {"square": "<img id='pic' src='img/15 La Pera.jpg'>"},
        {"square": "<img id='pic' src='img/16 La Bandera.jpg'>"},
        {"square": "<img id='pic' src='img/17 El Bandolon.jpg'>"},
        {"square": "<img id='pic' src='img/18 El Violoncello.jpg'>"},
        {"square": "<img id='pic' src='img/19 La Garza.jpg'>"},
        {"square": "<img id='pic' src='img/20 El Pajaro.jpg'>"},
        {"square": "<img id='pic' src='img/21 El Mano.jpg'>"},
        {"square": "<img id='pic' src='img/22 La Bota.jpg'>"},
        {"square": "<img id='pic' src='img/23 La Luna.jpg'>"},
        {"square": "<img id='pic' src='img/24 El Cotorro.jpg'>"},
        {"square": "<img id='pic' src='img/25 El Borracho.jpg'>"},
        {"square": "<img id='pic' src='img/26 El Negrito.jpg'>"},
        {"square": "<img id='pic' src='img/27 El Corazon.jpg'>"},
        {"square": "<img id='pic' src='img/28 La Sandia.jpg'>"},
        {"square": "<img id='pic' src='img/29 El Tambor.jpg'>"},
        {"square": "<img id='pic' src='img/30 El Camaron.jpg'>"},
        {"square": "<img id='pic' src='img/31 Las Jaras.jpg'>"},
        {"square": "<img id='pic' src='img/32 El Musico.jpg'>"},
        {"square": "<img id='pic' src='img/33 La Arana.jpg'>"},
        {"square": "<img id='pic' src='img/34 El Soldado.jpg'>"},
        {"square": "<img id='pic' src='img/35 La Estrella.jpg'>"},
        {"square": "<img id='pic' src='img/36 El Cazo.jpg'>"},
        {"square": "<img id='pic' src='img/37 El Mundo.jpg'>"},
        {"square": "<img id='pic' src='img/38 El Apache.jpg'>"},
        {"square": "<img id='pic' src='img/39 El Nopal.jpg'>"},
        {"square": "<img id='pic' src='img/40 El Alacran.jpg'>"},
        {"square": "<img id='pic' src='img/41 La Rosa.jpg'>"},
        {"square": "<img id='pic' src='img/42 La Calavera.jpg'>"},
        {"square": "<img id='pic' src='img/43 La Campana.jpg'>"},
        {"square": "<img id='pic' src='img/44 El Cantarito.jpg'>"},
        {"square": "<img id='pic' src='img/45 El Venado.jpg'>"},
        {"square": "<img id='pic' src='img/46 El Sol.jpg'>"},
        {"square": "<img id='pic' src='img/47 La Corona.jpg'>"},
        {"square": "<img id='pic' src='img/48 La Chalupa.jpg'>"},
        {"square": "<img id='pic' src='img/49 El Pino.jpg'>"},
        {"square": "<img id='pic' src='img/50 El Pescado.jpg'>"},
        {"square": "<img id='pic' src='img/51 La Palma.jpg'>"},
        {"square": "<img id='pic' src='img/52 La Maceta.jpg'>"},
        {"square": "<img id='pic' src='img/53 El Arpa.jpg'>"},
        {"square": "<img id='pic' src='img/54 La Rana.jpg'>"}
    ]
};
